### ISSUE TITLE
GCS - Outputs - Channel Assignment not populated.

### ISSUE THREAD

**Issue by xerovis** [TauLabs/TauLabs#1000]
When setting up board from scratch the Output channel assignment field is not populated unless I disconnect GCS from my board (not reboot) and then reconnect to board. It seems GCS is not polling for that information when it should be.

Occurs in Master and Next.

**Comment by elafargue** [comment]
Cannot reproduce in current GCS - issue is very old. Close ?

**Comment by elafargue** [comment]
Closing issue, current GCS does not have this issue - Output assignment updates on config widget as soon as channels are selected in vehicle.
