### ISSUE TITLE
Put Asseccory3 to 5 to the GCS

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#1010]
In Mixer I can use Asseccory 0 to 5, but in GCS I can only setup 0 to 2

I like to the the missing channels in the GCS for setup.
Even thru UAVObject Browser I only can setup Accessory 0 to 2

I meen min. , max. and reverse and so on

**Comment by mlyle** [comment]
Based on the decision to close and use picoc instead in #1018, closing.
