### ISSUE TITLE
GPS alarm does not update when GPS port is set to 9600bps or less

### ISSUE THREAD

**Issue by solidgoldbomb** [TauLabs/TauLabs#1066]
With a ublox GPS configured via the autoconfig mechanism, the main GPS loop never breaks out of the ````while (PIOS_COM_ReceiveBuffer())```` loop to set the alarm state.

Presumably, this is due to the receive call having a timeout of 100ms and the link being saturated at 9600bps and there are no gaps in the data stream where the loop would break out.

If you boot in this state, the GPS alarm state will remain as ````Uninitialized````.

Note that the GPSPosition UAVO is properly updated during the time when the GPS alarm is failing to be updated.

At 19200bps, it appears that we have some bandwidth to spare and the GPS mainloop manages to update the alarm state.

**Comment by mlyle** [comment]
Fixed by #1641 - we no longer wait 100ms for anything except the "first character".
