### ISSUE TITLE
Remove remaining instances of "REVOLUTION" flag

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1070]
This was used historically to include the more advanced code but
almost all cases use this code now. The #1054 removes another
instance but we have some in the GPS and simulation code.

It is better to use named flags, such as GPS_MINIMAL or whatever
to include options.

Then remove ```define REVOLUTION``` from all the flight targets.

**Comment by mlyle** [comment]
Resolved by #1745
