### ISSUE TITLE
Sparky: memory limitations

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#1071]
I use Sparky with Next from 2014-01-02 00:30
When I use only Mavlink on Flexport, my OSD work perfekt.
But when I use Mavlink / GPS, OSD only say "no Data"

When I switch back to Mavlink only, but without changing the rest of the settings, OSD work perfekt again.

**Comment by jdvann** [comment]
I was have trouble with GPS and VtolPathFollower causing a boot fault, but after reading this post I was able to determine that I still had auto tune enabled and when I disabled auto tune I was able to enable GPS and VtolPathFollower. I hope this helps someone else. I wish that I had learned how to save the settings before this boot falt. I will have to fly autotune again.
