### ISSUE TITLE
Strip out cruft from paths.c and follower

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1077]
Currently we have redundant modes like "FlyEndpoint" versus "DriveEndpoint" which is a distinction without behavior. We might as well strips things like this out. They are only considered in the path.c file. There we should only be concerned with actual path segments.

Things holding an endpoint are handled in paths.c but not used anywhere I see.

**Comment by mlyle** [comment]
Resolved by #1669
