### ISSUE TITLE
Add UAVO information to logfiles

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#111]
Currently, logfiles only have a small amount of information about the GCS and UAVO structure that was used to generate the log. It would be nice to include all the UAVO information required to read the file into a header.

Probably the fastest and easiest way to do this is to structure the logfile like an xml file, where the UAVOs are in the beginning and then the data section is just the binary UAVTalk stream.

We could also consider some approach like with kml/kmz, where the entire file is generated as an xml file, where every UAVTalk packet is exported into an XML entry.

**Comment by peabody124** [comment]
The python parser handles old log files gracefully by reading the header and pulling the relevant XML files from git.
