### ISSUE TITLE
Add Flight Mode support to MavLink protocol

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#1110]
Actual we don't have the flight mode in MavLink HeartBeat.

I like to add this.
The Problem; our IDs didn't fit to the flight mode IDs from MavLink.

Only this are in Mavlink
Stabilization1    = Mavlink = Stab
AltitudeHold      = Mavlink = alth
PositionHold     = Mavlink = posi
ReturnToHome  = Mavlink = retl (Return to launch)

I ask the MinimOSD developer to add our 'missing' mods, but he didn't like to do it, because he like to stay compatible to APM.
APM is using IDs up to 13 in the moment.

Any idea how to deal with that?
Ok, we can fork the actual code and patch.
But thats additional work, to keep the code up to date 

cu
Carsten

**Comment by mlyle** [comment]
Fixed by #1795
