### ISSUE TITLE
qt5 MacOSx cosmetic bug

### ISSUE THREAD

**Issue by KipK** [TauLabs/TauLabs#1133]
Nothing important, there a little cosmetic bug at startup. The loading message output stays blank under the logo on macosX 

![capture d cran 2014-03-09 12 39 58](https://f.cloud.github.com/assets/488789/2367839/ec938af2-a77f-11e3-9018-6bb3c694aa09.png)

**Comment by peabody124** [comment]
Yeah that stupid splash screen on OSX drives me nuts!

**Comment by mlyle** [comment]
Doesn't stay blank for me-- can this be closed?

**Comment by peabody124** [comment]
This is a real bug - the progress bar does not advance on OSX. It stops at random points for people and even different points for the same person different launches. I'm not sure if it is a duplicate though.

**Comment by mlyle** [comment]
Duplicate #1431
