### ISSUE TITLE
Disable motors while inverted in altitude hold

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1157]
Altitude hold should disable the motors while inverted. This typically only happens while
crashed.  However ... a big consideration of this is that if that happens you lose any stabilization so if you clip something in this mode and go past 90 deg you would have to exit AH mode before it could stabilize.

I'm not certain the best approach. Upside down for more than 3 seconds, then disable?

**Comment by mlyle** [comment]
Since 91140f4a4, when tilt compensation is enabled throttle goes to 0 when past ~80 degrees.  Attitude/tilt compensation defaults on.  OK to close?

**Comment by mlyle** [comment]
Closing.
