### ISSUE TITLE
Stabilized mode + GPS lock

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1158]
This was a suggestion from OsoGrande, and I think is similar to the hybrid mode in Ardupilot. It would be fun to have a flight mode that is an attitude (rate?) controller for normal flight. However, when you release sticks it tries to enables a position hold.

Some subtly might be required in terms of how it bleeds of momentum before entering a hold.

**Comment by brat002** [comment]
+1 very useful feature for learning acro.

**Comment by mlyle** [comment]
I'm working on a "zippy loiter" mode, which is related, but it's not quite an attitude controller.

**Comment by brat002** [comment]
Very promising comment! Will wait for these changes.

**Comment by mlyle** [comment]
The code in question is in PR #1679, which I plan to work on more in the next week.

**Comment by mlyle** [comment]
Merged!
