### ISSUE TITLE
Wrong flight time calculation

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#1190]
I realise a easy voltage measurement with to resistors 1k/3k83 for 3S
Calibration factor: 208,7 mV/V
In Modules setting I switch OFF current measurement.

But:
- Current is shown with utopic values
- flight time is calculated with this wrong current

Workaround:
Calibration factor: 999,9999 mV/A

**Comment by mlyle** [comment]
Unchecking the checkbox correctly sets current input to "NONE" on save now.  So fixed.
