### ISSUE TITLE
runtime error 

### ISSUE THREAD

**Issue by vargasesteban** [TauLabs/TauLabs#1227]
version : TauLabs-20140405-ab688254
os : Windows 8.1  32 bits
when i click  on Flight Data Tab (HUB)
Always get runtime error , then says taulabs stop wirking and the program exit.
![tlproblem](https://cloud.githubusercontent.com/assets/5982266/3910980/193ff9e6-231d-11e4-8ead-12cff717398d.png)
![tlproblem1](https://cloud.githubusercontent.com/assets/5982266/3910981/19427e0a-231d-11e4-891a-fd7064998371.png)

**Comment by peabody124** [comment]
closed due to inactivity
