### ISSUE TITLE
Pipxtreme broken in recent Next

### ISSUE THREAD

**Issue by carbogit** [TauLabs/TauLabs#1260]
I believe that support for Pipxtreme/Oplink is broken in recent versions. Settings are grey in configuration and object browser and cannot be saved.

**Comment by mlyle** [comment]
Binding wizard makes this happy / I use pipxtreme all the time.

**Comment by solidgoldbomb** [comment]
Closing this.  Should be fixed by #1451.  Feel free to re-open if it's not fixed in builds that include #1451.
