### ISSUE TITLE
Remove feedforward code

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1359]
This was from the days of old ESCs and terribly hard to tune anyway. This code is no longer needed in either the GCS or in the Mixer.

**Comment by peabody124** [comment]
@elafargue btw if you are still interested in this, i'd say it would be great to strip out the GCS code sooner rather than later. that way if anyone is still using it the firmware will still support it and we can figure out why.

**Comment by elafargue** [comment]
This issue is fixed on the GCS side. Shall we close it and open a separate issue to remove FF on the flight side ?

**Comment by elafargue** [comment]
Closing and opening an issue for flight-side FF code removal.
