### ISSUE TITLE
SBus on Revo(Mini) does not work

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1368]
It has been reported on the forums that SBus with Revo does not work.

http://forum.taulabs.org/viewtopic.php?f=20&t=287

**Comment by totosolat** [comment]
Hi,

I had the same issue with two sparky and futaba R2008SB receiver.
The RX status (from system health) was green but sometimes had a quick "No RX" error which causes the failsafe to stop the motors. (The "No RX" error is showing for a short time, about .5 seconds)

I use the same receiver with a Quanton and never had such behaviour.

Applying the patch scenkov proposed solved this issue for me. Thanks a lot!

I'm quite confused about this issue as I didn't find any known issues with sparky and futaba receiver (am I doing something else wrong?). I also don't understand why it is different with the Quanton as pios_sbus.c is common.

**Comment by peabody124** [comment]
this has been fixed by 98dc5e6956e97d982475e1b15199dc291b72eafe
