### ISSUE TITLE
Windows 8.1 x64 font's

### ISSUE THREAD

**Issue by Zyamstein** [TauLabs/TauLabs#1379]
Font's in the preview and flight data
welcome - https://yadi.sk/i/DEfGoNTUcL2HS
and
flight data https://yadi.sk/i/wpsbBaPqcL2S9

**Comment by Zyamstein** [comment]
localised this problem
it is hapenes  on onboard intel 4 series videocard
screen with intel videocard
https://yadi.sk/i/7Tlh6krTfdRa3 and https://yadi.sk/i/mpxTvGbgfdRbc
and now on the same computer with radeon hd card
https://yadi.sk/i/iLPZ5nLAfdRe7 and https://yadi.sk/i/7sT_f3UYfdRfA

**Comment by mlyle** [comment]
@Zyamstein can you please upload these screenshots to github if you still have them?  These links are dead unfortunately.

**Comment by mlyle** [comment]
Closed INVALID due to lack of details.
