### ISSUE TITLE
Specific config options for Ublox 8 series

### ISSUE THREAD

**Issue by henkf** [TauLabs/TauLabs#1394]
The Ublox 8 modules allow for simultaneous use of GPS and GLONASS, also a higher rate with a measurement period of 56ms.
The following two messages can be incorporated into the ublox autoconfig to take advantage of these possibilities.

`CFG GNSS`
`0000|  B5 62 06 3E 2C 00 00 00 20 05 00`
`000B|  08 10 00 01 00 01 01 01 01 03 00`
`0016|  01 00 01 01 03 08 10 00 00 00 01`
`0021|  01 05 00 03 00 01 00 01 01 06 08`
`002C|  0E 00 01 00 01 01 FF 3D`   

`CFG RATE`
`0000|  B5 62 06 08 06 00 38 00 01 00 01`
`000B|  00 4E 0A`

**Comment by peabody124** [comment]
for reference this link: https://u-blox.com/images/downloads/Product_Docs/u-bloxM8_ReceiverDescriptionProtocolSpec_(UBX-13003221)_Public.pdf contains the message definitions

GNSS identifiers:
0 GPS
1 SBAS
2 Galileo
3 BeiDou
4 IMES
5 QZSS
6 GLONASS

breaking down the CFG GNSS message pasted above:
B5 - sync1
62 - sync2
06 - CFG
3E - GNSS
2C - length lsb
00 - length msb
 -- payload
00 - msgVer
00 - read only
20 - number of channels to use
05 - number of configuration blocks

00 - GNSS identifier (GPS)
08 - minimum channels
10 - maximum number of tracking channels
00 - reserved
01 00 01 01 - bitfield of flags

01- GNSS identifier (SBAS)
01 - minimum channels
03 - maximum channels
00 - reserved
01 00 01 01 - bitfield of flags

03 - GNSS identifier (BeiDou)
08
10
00
00 00 01 01

05 - GNSS identifier (GZSS)
00 - min
03 - max
00 - reserved
01 00 01 01

06 - GLONASS
08 - min
0E - max
00 - reserved
01 00 01 01 - flags

FF - checksum 1
3D - checksum 2

**Comment by peabody124** [comment]
You have any source for the claim of 56 ms processing loop on UBlox 8? In the datasheet it says to use 5 Hz for max navigation update rate in dual modes for NEO-M8N https://u-blox.com/images/downloads/Product_Docs/NEO-M8_DataSheet_(UBX-13003366).pdf

**Comment by henkf** [comment]
I found this rate in the manual of the reyax m8n module from ebay. By the time I tested some other ubx 8 modules and the rate should definitely be lower, like you said. I will revise those settings.

**Comment by peabody124** [comment]
you don't need to recompute the message. we have a ```set_rate``` command:
https://github.com/TauLabs/TauLabs/blob/next/flight/Modules/GPS/ubx_cfg.c#L142

I'm trying to figure out the flags though. i don't understand why they are ```01 00 01 01``` for most that are enabled. if you look in the data sheet the first 01 is enable, the third is the GNSS system configuration. The fourth one seems unnecessary...
![screen shot 2015-03-24 at 4 24 08 pm](https://cloud.githubusercontent.com/assets/618346/6813297/4f2dd972-d242-11e4-8152-44b3de169ecb.png)

**Comment by peabody124** [comment]
I'm also curious if half the rate with more satellites will be better or worse. This will need testing.

**Comment by henkf** [comment]
I took those flags straight from u-center.

Making qualitative statements about the relation between rate and number of satellites may be a difficult endeavour under varying reception in different locations. But it is certainly worth trying.

I will review this once i'm back home and did some further testing with my modules.

**Comment by peabody124** [comment]
This still needs flight testing before we know iti s a good default. Moved to July release milestone.
