### ISSUE TITLE
Show live channel bars/values on "RC Input" and "Flight Mode Switch Settings" tabs

### ISSUE THREAD

**Issue by DTFUHF** [TauLabs/TauLabs#1405]
This issue is basically to ask for improvements to the Input page of GCS configuration. It will make input/controller setup smoother and easier for everybody to be able to get live feedback on your inputs.

I'd like the following:

-Live input channel values viewable
-Live channel values viewable on top of the bars for setting neutral/endpoints
-Live Flight Mode channel value viewable on top of the Flight Mode Switch Positions bar on that tab
-Configurable break-points for the FlightMode Switch
-A better tooltip explanation of what the Throttle Neutral point does and what it's for
-A warning that clicking Manual Calibration will instantly erase all of your input endpoint settings

**Comment by mlyle** [comment]
It's not shown as a bar (art above looks cluttered), but ffec18f5 / #1634 adds a column to show the current value.
