### ISSUE TITLE
Dropped out of the sky 

### ISSUE THREAD

**Issue by tbs-trappy** [TauLabs/TauLabs#1413]
Hovering gently in Stabilized2 (RateMW / RateMW / RateMW), switched to AltitudeHold and it dropped out of the sky. When it was upside down the motors were spooling up and down, locking the motors did not work even after several attempts. The flight control had a constant red LED on, no other LEDs (Green or Blue) were on. After some time it shut down and you coud hear the ESCs beep, signalling loss of PWM on the motor outputs. 

My UAV file:
https://gist.github.com/tbs-trappy/c3473d741e3b75a46ca5

**Comment by peabody124** [comment]
This was ruled out as a software bug.
