### ISSUE TITLE
Increase code flash on F4 targets

### ISSUE THREAD

**Issue by ernieift** [TauLabs/TauLabs#1425]
The code grows. The more functionality it gets, the more flash it eats. We are getting out of flash memory on f4 targets. I think it it time to reorganize the code space on this targets. This requires an updated bootloader, i think. This could be a goal to the next master release.

**Comment by peabody124** [comment]
Also lets bump this after the Jan release. It's likely we'll be moving towards a chibios merge then so lots of updates.

**Comment by peabody124** [comment]
This is updated for Quanton now.

**Comment by peabody124** [comment]
This has been updaetd for all targets it will be
