### ISSUE TITLE
Welcome plugin broken on next

### ISSUE THREAD

**Issue by guilhermito** [TauLabs/TauLabs#1426]
After 8da04122a8f460e0c73532dba129f80bd01f2f05 the plugin got broken on Ubuntu 64. First time displayed it looks ok but doesn't respond to mouse clicks. Going to another tab and back shows the plugin as a black rectangle. Reverting the commit above fixes it.

**Comment by peabody124** [comment]
Looks like there is a segfault on exit now. I think because of the fix for this:
http://forum.taulabs.org/viewtopic.php?f=18&t=480&start=10#p4037

**Comment by solidgoldbomb** [comment]
Is this fixed by the two merges above?

**Comment by peabody124** [comment]
Yep!
