### ISSUE TITLE
Tau Labs GCS Crashes on OSX Yosemite 10.10

### ISSUE THREAD

**Issue by UKTamo** [TauLabs/TauLabs#1430]
Hi,

Running OS X Yosemite 10.10.
GCS Crashes immediately on startup.
Running TauLabs-20141026-1f8fa2fe

**Comment by guilhermito** [comment]
Can you post the crash report?

**Comment by UKTamo** [comment]
Apologies, I realised this is the wrong fork to raise this against. Raising against BrainFPV fork.
