### ISSUE TITLE
Warning about Integral Settings

### ISSUE THREAD

**Issue by x0054** [TauLabs/TauLabs#1434]
So, I admit it, I didn't properly read the OpenPilot manual about Stabilization page. So, this is mostly my bad, by I would like to add a request to add a warning about setting the Integral setting in BOTH, the Inner and Outer loop to a non zero value. Setting both values to a nonzero makes the multirottor crash in a hurry. Maybe a warning that pops up saying something like:

"Setting Integral value in both the inner and outer loop to a nonzero value will very likely result in a crash. Are you sure you would like to proceed?"

**Comment by mlyle** [comment]
Integral in both loops can be sane, though you usually want a pretty low value in the outer loop.
