### ISSUE TITLE
macdeployqt broken in Qt 5.4 which breaks packaging

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1442]
As reported by balu, the welcome screen is broken again. There is a regression in macdeployqt for Qt 5.4:

https://bugreports.qt.io/browse/QTBUG-43100
https://bugreports.qt.io/browse/QTBUG-42952
https://bugreports.qt.io/browse/QTBUG-42954

http://forum.taulabs.org/viewtopic.php?f=18&t=480#p3846

**Comment by peabody124** [comment]
For now there is a workaround for this. Compile Qt5.4.0 with the patch from here https://bugreports.qt.io/browse/QTBUG-42954 when packaging OSX. This is more appealing than continuing to hold OSX back a version compared to the other operating systems, and the fix should be applied in Qt 5.4.1.

**Comment by peabody124** [comment]
I'm removing the blocker label on this because there is a workaround currently (recompiling Qt with the patch on macdeployqt). I'll leave it open until Qt 5.4.1 is released and we confirm that fixes the root issue.

**Comment by mlyle** [comment]
Hack workaround merged in #1703; when we pick up 5.5.0 it should be reverted.

**Comment by mlyle** [comment]
Fix merged, yaaay.
