### ISSUE TITLE
GCS: Restore Setting from saved file

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#1456]
I wonder, why battery and HoTT is not set after import the file:
![image](https://cloud.githubusercontent.com/assets/2094549/5887219/aa257748-a3c3-11e4-831e-3d885d7ecf64.png)
Why this error messages?
Error (Object present on HW?

**Comment by peabody124** [comment]
You need to do it twice - once to enable the module, then power cycle, then import again. Those objects are not known to the system if the appropriate module is not running.
