### ISSUE TITLE
Missing DLLs in Master Windows from 2015.01.31

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#1472]
taulabs_master_20150131_232019_4082e9d88c_win32

After starting GCS on Windows 8.1 x64
![image](https://cloud.githubusercontent.com/assets/2094549/5993388/21da5ccc-aa4f-11e4-8d2c-ed31b2bdd122.png)

**Comment by peabody124** [comment]
Installer or portable version?

**Comment by cGiesen** [comment]
I have only extract the file I download here:
http://jenkins.taulabs.org/artifacts/taulabs_master_20150131_232019_4082e9d88c_win32.exe

**Comment by guilhermito** [comment]
Are you sure the plugins are missing? That message looks like it is trying to load plugins from a previous build.

**Comment by mlyle** [comment]
I ran this build successfully on windows 8.1 x64.  Does this still happen, @cGiesen, or were you able to make it work??

**Comment by mlyle** [comment]
Closed INVALID due to lack of details.
