### ISSUE TITLE
Error enabling Autotune on Quanton, Sparky, CC3D and CC

### ISSUE THREAD

**Issue by pug398** [TauLabs/TauLabs#1473]
Pre release 20150131-4082e9d8 Win7 32bit

Opening this to get it out of the way. Quanton and Sparky give System Ident error on autotune enable but module does enable. Warning is given on first save attempt and red X on second.

Autotune enable has generated Boot Fault on CC3D and CC since release after 10_26_14. Works on 10_26_14 does not work on 11_26_14 if it helps.

**Comment by peabody124** [comment]
Thanks for the report. What do you mean they give "System Ident error on autotune enable?

**Comment by peabody124** [comment]
Ok I see it from a screenshot that was attached on forums (duplicated here).

![tlprob1](https://cloud.githubusercontent.com/assets/618346/6008403/ce07ae90-aae6-11e4-8e2f-58ac87e48a61.png)

That is a purely UI bug. The autotune page does not need to save or even send the SystemIdent settings. Previously it was a data object so the widget did not even try, but we changed to a setting so people could power down after running SystemIdent.

@guilhermito do you have any suggestions? I'd like to keep the automatic signals from the smart system but not have it try and apply or save the ```SystemIdent``` object. If there isn't an easy workaround I can just directly update the fields based on the object...

**Comment by peabody124** [comment]
I created a separate issue for CC3D autotune.

**Comment by guilhermito** [comment]
Sorry no time to look at this right now but it should be fixable just by using "setNotMandatory" created on #1386

**Comment by pug398** [comment]
I see you are already on top of it. Thanks.

**Comment by mlyle** [comment]
Fixed by #1650.
