### ISSUE TITLE
Automatic leveling detection

### ISSUE THREAD

**Issue by Zyamstein** [TauLabs/TauLabs#1488]
After six point calibration,  leveling detection is lost.

GCS pre release 20150131-4082e9d8
FC Qunton
Windows 8.1

**Comment by peabody124** [comment]
This is not a bug. This is the expected behavior. You should level after 6pt

**Comment by peabody124** [comment]
To elaborate on my previous point - 6 point calibration determines a new magnitude and bias of the sensors. After performing this the angle you were rotated by previously will have a different effect. The solution to this to run 6 point first, and then leveling second. That is why they are laid out in that order on the GCS.
