### ISSUE TITLE
Remove "Max rate attitude (deg/s)" from GCS GUI

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1496]
This should probably stay as a parameter available in the browser, but
there is never a real time that the end user needs to adjust this to get
a desired flight style. In fact, I always have to look up what it does by
going through both the GCS code and the flight code.

Basically we want to keep the rate mode max rate and max angles.

**Comment by elafargue** [comment]
... by the way: what _does_ it do ? :)

**Comment by peabody124** [comment]
in attitude mode it limits the rate that the outer loop can request. It isn't very common to hit 300 deg/s in attitude mode though so it has little practical effect.

**Comment by elafargue** [comment]
OK, will update GCS UI, should be pretty straightforward.

**Comment by elafargue** [comment]
This is now fixed.
