### ISSUE TITLE
Add "Cancel" button

### ISSUE THREAD

**Issue by Zyamstein** [TauLabs/TauLabs#1505]
It will be good to add Cancel button on all steps of ESC Calibration

Today I try to make and realized that props or in the motors and decide to put it out, but I have a lack of space and want to cancel the ESC calibration to safely put them down - but there was no options and I press the Esc key and motors spenn to maximum... Everything else I think every body know what's happens :)

**Comment by mlyle** [comment]
#1818 merged, closing
