### ISSUE TITLE
Logging module: file header invalid

### ISSUE THREAD

**Issue by BrainFPV** [TauLabs/TauLabs#1507]
I have been trying to use the new logging module on the Brain FPV FC, but when I download the log and try to open it using the Python parser, I get an error stating the header of the file is invalid. Has anyone else experienced this problem or are extra steps needed to open the file?

**Comment by BrainFPV** [comment]
ping @peabody124 when logging with Android, I see a header of the form below, but it isn't present when logging with the internal module. Is this expected? 

    Tau Labs git hash:
    66d34c53
    95ed7f467993fa474dda95392d0c77e6b59efd4e

**Comment by BrainFPV** [comment]
The log file is valid, but the header is missing. I can read it using a modified version of the Python parser.

A solution would be to write the version info at the start of the internal log file and the GCS formats it properly when exporting. Thoughts?

**Comment by peabody124** [comment]
@BrainFPV yeah that sounds like a great idea!

**Comment by BrainFPV** [comment]
I will look into it. 

Also, I had some ideas how to make logging more useful for regular users. First, it would be nice if the GCS would show a list of logs and the date when the flight occured. To get the date, we could add some functionality to the logfs to get the GPS time for each log file (it would just look for the first good GPS time entry). Second, the GCS should offer the option to export the log as a KML file (it would just parse the GPSPosition objects and export the results to the KML format).

**Comment by peabody124** [comment]
Yeah I think both of those would be quite useful. Another option would just be a python script that essentially does that to a bunch of log files in a directory. But integrating into GCS is probably the most user friendly thing.

**Comment by elafargue** [comment]
@BrainFPV I love the KML export idea - what I would like to see is an option to include additional UAVObjects inthe KML export: for instance, if you want a KML that also contains your battery level, or barometric pressure or other. Would be super useful.

**Comment by elafargue** [comment]
@BrainFPV there is a KML export plugin in the GCS that is disabled by default, have you tried it? IMHO if this is simply a log file conversion plugin, it should be either moved as a separate utility outside of the GCS, or it should be turned into another type of log export format ? Thoughts? Shall we open a separate issue on this?
