### ISSUE TITLE
lag's with next_20150321

### ISSUE THREAD

**Issue by Zyamstein** [TauLabs/TauLabs#1512]
windows 8.1
Videocard - Intel 4 series
taulabs next_20150321
disappear systemhealth and pfd gadgets
and
welcome screen lug https://yadi.sk/i/wCaUzfGsfSbXE

after clean configuration gadgets is back

**Comment by mlyle** [comment]
Can you please provide more information?  The bug is for the GCS being laggy-- is this a regression from previous releases?  It looks like the linked picture is gone-- can you upload to Github?  Thanks!

**Comment by mlyle** [comment]
Closed INVALID due to lack of details.
