### ISSUE TITLE
Sparky after Chibios: enable GPS and bootloop

### ISSUE THREAD

**Issue by sfabris** [TauLabs/TauLabs#1515]
So,

I've able to replicate this:
- clean sparky (erase all settings from board);
- flash next (after chibios merge)
- reboot
- enable GPS module and set an uart to GPS (i.e. Flexi)
- reboot
- bootloop.

If I try rescue, then safe boot: also bootloop.

I'm sorry but I don't have the knowledge to help on this more than opening this issue..

**Comment by peabody124** [comment]
Thanks for the report! I'll look at it soon

**Comment by peabody124** [comment]
Ok. This is because ChibiOS doesn't play nicely with stack sizes that aren't ```aligned(8)```.  Working on a fix that will prevent this error again.

**Comment by peabody124** [comment]
@sfabris can you confirm this is fixed on next for you now?

**Comment by sfabris** [comment]
Works properly!. 
Thanks for the fix.
