### ISSUE TITLE
flyingf4 real-time clock divider

### ISSUE THREAD

**Issue by bostontim** [TauLabs/TauLabs#1525]
The flyingf4 real-time clock divider appears incorrect which results in inability to receive sbus signals.  To fixed this problem I needed to change the follow code in flight/targets/flyingf4/board-info/board_hw_defs.c.

-	.clksrc = RCC_RTCCLKSource_HSE_Div16

+	.clksrc = RCC_RTCCLKSource_HSE_Div8

**Comment by peabody124** [comment]
Could you make a pull request that applies these fixes?

**Comment by bostontim** [comment]
Will do.

**Comment by bostontim** [comment]
Entered my first pull request.  Please let me know if I did it correctly.  Thanks.

**Comment by kubark42** [comment]
Fixed by #1540.
