### ISSUE TITLE
Input wizard seems to disregard the center position

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1526]
I think the input wizard might be takign the min+max average rather than the empirical center position. For transmitters that do not have well centered pots, this can create weird things.

**Comment by lolorc** [comment]
I *might* have encountered this one.
If I have, it happened on an inverted sbus input, ChannelMin=1811, ChannelMax=172, ChannelNeutral was set to 1811
I did use input wizard not that long ago but I can't affirm ChannelNeutral was altered by the wizard, might as well been pebcak :)

**Comment by elafargue** [comment]
Fixed with #1552
