### ISSUE TITLE
I2C virtual machine GUI

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#155]
A while ago, I wrote a GUI and compiler to complement the I2C virtual machine that stac wrote. Unfortunately, while the compiler worked the resulting GUI was poor. This issue is for updating the GUI.

The specific issue was that the GUI layout was inconsistent and behaved poorly.

**Comment by mlyle** [comment]
That tree is now missing, and we're doing less with I2C in general.  Any objections to me closing this?

**Comment by tracernz** [comment]
https://github.com/kubark42/TauLabs/tree/kenz/genericI2C_compiler ;)

**Comment by mlyle** [comment]
@tracernz :)  Well, is it useful to have in the main distribution?  It doesn't feel like something urgent to clean up and it's been rotting for a couple years..

**Comment by mlyle** [comment]
No objections to close.
