### ISSUE TITLE
Missing artifacts for sparky2 on linux, windows

### ISSUE THREAD

**Issue by mlyle** [TauLabs/TauLabs#1606]
@peabody124 

@lilvinz It looks like the packaging script for linux at least contains for b in coptercontrol pipxtreme revolution revomini osd freedom 
              quanton flyingf3 discoveryf3 flyingf4 discoveryf4 sparky sparkybgc 

and should contain sparky2.  Can you please fix when you get a chance?   :)

**Comment by peabody124** [comment]
Relevant issue: #1228

**Comment by peabody124** [comment]
This is fixed now.
