### ISSUE TITLE
GCS crash on File->Import Waypoints

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1612]
The import waypoints works through the gadget but the File menu just crashes.

**Comment by elafargue** [comment]
It's an easy fix, but the underlying issue is that the file format on the File menu is inconsistent with the file format in the pathplanner gadget.

My suggestion is to drop the waypoint export menu entry, it is duplicating the functionality of the pathplanner gadget. Thoughts ?

**Comment by peabody124** [comment]
Can't it call the working method?

**Comment by elafargue** [comment]
I'll look into it.

**Comment by mlyle** [comment]
Fixed by #1639.
