### ISSUE TITLE
UBX should reconfigure while "NoGps" or if messages missing

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#1617]
If you apply power via USB before the GPS or disconnect/reconnect the GPS then you will not have a configuration. The system should repeatedly send the autoconfiguration messages (e.g. once every 10 seconds) if the status is NoGps. possibly also if some messages (e.g. NEDVEL) are never seen.

**Comment by DTFUHF** [comment]
Probably better idea is a simple state machine that can detect and recover
from configuration and communication problems. That can also handle
autobauding. Simpler FCs like baseflight already do this.

**Comment by peabody124** [comment]
We already have autobauding. It is just deciding when to call it.

**Comment by DTFUHF** [comment]
Yes, I meant a GPS communication state machine could handle this as well.

**Comment by elafargue** [comment]
This is fixed by #1641
