### ISSUE TITLE
ManualControl crashes on CC3D

### ISSUE THREAD

**Issue by ernieift** [TauLabs/TauLabs#1619]
Just found an issue on CopterControl. There is a
```
#define PIOS_MANUAL_STACK_SIZE          600
```
in pios_config.h. After the last merges the target crashes when the receiver should go on green. My quick workaround was this.
```
#define PIOS_MANUAL_STACK_SIZE          620
```
I tested the protocols HOTT_SUMD/SUMH. Eventually DSM has the same issue. This only happens on CopterControl. Other targets uses 1000 bytes stack. Before I make a PR for this I would prefer a more deeper analysis.

**Comment by peabody124** [comment]
I would recommend a PR that increaes it a whole 100. It isn't useful to be so close, and gradually CC3D is just going to loose features. We really should recommend people just stick with the December release.

**Comment by ernieift** [comment]
Solved by increasing stack on CC3D.
