### ISSUE TITLE
GCS: Default log output on OSX doesn't work

### ISSUE THREAD

**Issue by mlyle** [TauLabs/TauLabs#1629]
If you start GCS by double clicking on it or open "Tau Labs GCS.app" at the command line, the default save location for logs is Macintosh HD.  By default users do not have write permission to this location on OSX so the log fails, silently.

The default should be changed and if there is a failure opening the log for writing, a dialog should pop up to inform the user of this fact.

**Comment by elafargue** [comment]
This is now fixed.
