### ISSUE TITLE
OPMap: map config contains a default home location, which interferes with actual UAV Home location

### ISSUE THREAD

**Issue by elafargue** [TauLabs/TauLabs#1643]
The OPMap gadget configuration contains a default home latitude and longitude. This is also used to set the map's Home location icon (the little house) from the configuration when the map configuration is loaded. 

Setting the home location on the map from the map's settings should be avoided, the map gadget should only use the home location that is present in the UAVObjects.

Proposed action: stop setting the map home location from map's default latitude/longitude

**Comment by elafargue** [comment]
Any further comment on this ? I'd like to push a PR on this and close the issue if no one objects

**Comment by mlyle** [comment]
I'm fine with this.

**Comment by mlyle** [comment]
Merged in #1639
