### ISSUE TITLE
"zero gyros while arming" not always working.

### ISSUE THREAD

**Issue by ernieift** [TauLabs/TauLabs#1656]
A few days ago, i had an issue with my light weight racing copter. After arming and liftoff the copter was spinning and simply uncontrollable. I was outside and couldn't check any variables. Yesterday i had the same issue. Now i have found the reason: "zero Gyros while arming" doesn't work when you use a switch for arming.
You can reproduce the bug this way. Connect your vehicle via usb and move it around for about 10 seconds. You can see in the gcs all gyros have offsets now. If you set your arming settings via stick movements, these offsets were zeros while arming. If you use a switch for arming, the offsets are untouched.

**Comment by peabody124** [comment]
Fixed by #1657
