### ISSUE TITLE
Graupner PPM: only usable for <12 channels

### ISSUE THREAD

**Issue by beckerth** [TauLabs/TauLabs#1672]
When using a Graupner Hott Receiver GR-16 and activating more than 12 channels the RC input is not recognized any more.

**Comment by tracernz** [comment]
The max PPM channel limit is set to 12 e.g. [Sparky2](https://github.com/TauLabs/TauLabs/blob/next/flight/targets/sparky2/board-info/pios_board.h#L200). Jeti supports either 8 or 16 channels on PPM with the latest firmware so perhaps this should be revisited, although perhaps there is a good reason for the 12 channel limit?

**Comment by mlyle** [comment]
What do you ever do with all those channels? ;) roll/pitch/yaw/throttle/flightmode/arming/camerar/camerap/cameray/accdesired1/accdesired2 just gets me to 11..

If there's a decent use case for all the channels I'm glad to look through pios to see why the limit is there.

**Comment by tracernz** [comment]
The problem with the Jeti implementation at least is that you can either have 8 or 16, nothing between.

**Comment by mlyle** [comment]
ah, that makes sense.  I will try and look at this at some point.

**Comment by beckerth** [comment]
12 channels should be fine. I found nothing about that in the wiki and it took me some hours to find out why the receiver wasn't recognized... 
So an update of the wiki page will more or less close the issue?! https://github.com/TauLabs/TauLabs/wiki/User-Guide:-Connect-Receiver

**Comment by ernieift** [comment]
Why not use SUMD for this problem? SUMD can handle up to 32 channels and all channels are transferred within one frame in 11 or 22ms. PPM and 12 channels take more than 12*2ms = 24ms at least.

**Comment by mlyle** [comment]
Duplicate #818
