### ISSUE TITLE
GCS Crashes on start

### ISSUE THREAD

**Issue by robertkr78** [TauLabs/TauLabs#1717]
On first install GCS crashes.
Intel graphics card !
![error](https://cloud.githubusercontent.com/assets/13311173/8645656/94313876-2949-11e5-9119-567313dfca6c.png)

**Comment by peabody124** [comment]
what version? is this the latest pre-release?

**Comment by guilhermito** [comment]
Can you try this https://github.com/TauLabs/TauLabs/wiki/Running-the-GCS-on-non-OpenGL-2.1-capable-systems

**Comment by robertkr78** [comment]
It worked with OpenGL 2.1 !!

Thanks !
![version](https://cloud.githubusercontent.com/assets/13311173/8651696/c2ff7240-297a-11e5-9fa7-42438e461802.png)

**Comment by peabody124** [comment]
@mlyle has been looking at a better fix on top of Qt5.5 but this will be in the next release.
