### ISSUE TITLE
Attitude task doubles in CPU usage with high frequency (250hz) gyro lpf

### ISSUE THREAD

**Issue by fujin** [TauLabs/TauLabs#1724]
![2015-07-17-105220_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6873/8737697/3be038d8-2c79-11e5-9a27-1a6cc1429740.png)

Reproduced on Brain-20150714. Dropping back to 184hz brings the cpu down to 7% on the Attitude task.

**Comment by fujin** [comment]
@BrainFPV :ocean:

**Comment by BrainFPV** [comment]
@fujin this is a limitation of the MPU9250; when the lpf is 250Hz, the MPU9250 is running at 8KHz, thus causing crazy CPU usage. I removed the 250Hz option for Brain, the same should probably be done for sparky2. 

I know you would probably like it, as it should give a super low tau in auto tune ;).

**Comment by fujin** [comment]
when #1726 lands we can consider this resolved I think. We should maybe document the issue for future MPU9250 targets?

https://github.com/BrainFPV/TauLabs/commit/af84efa74130d1afdf08712206d8b4fef5520e0f

**Comment by mlyle** [comment]
Fixed for now with #1726
