### ISSUE TITLE
CC3D Autotune, Boot Alarm

### ISSUE THREAD

**Issue by JurajKabzan** [TauLabs/TauLabs#1733]
Hello,

I flashed newest(build from source and also from latest release) fw to my cc3d board, enabled Autotune. After saving all settings and restarting, cc3d boots but with boot alarm. This alarm is writing that cc3d failed more than 3 times to boot and all setting will be default. Did anybody walked throught this problem? Thank you

**Comment by mlyle** [comment]
@JurajKabzan Autotune works on current CC3D in the simplest cases but uses nearly all memory.  Did you have any modules other than autotune turned on?  What kind of receiver are you using?

**Comment by mlyle** [comment]
@JurajKabzan any details, please?
