### ISSUE TITLE
Can not update firmware to 20150713-4b9fc7dc46 on Quanton

### ISSUE THREAD

**Issue by JeromePilot** [TauLabs/TauLabs#1747]
Hi,

My quanton is on firmware 20150131-4082e9d8. I have flashed it easaly under the GCS under XP several times without pb. 

After update with "Windows (installer)" to 20150713-4b9fc7dc46 the quanton is seen (it says me the firmware is the matching 20150713) but not possible fo flash the new firmware, got a red error message. 
I tried to flash using the 20150131-4082e9d8 GCS : no problem to flash 20150131-4082e9d8 firmware but impossible to flash 20150131-4082e9d8 neither under the previous GCS.

I suspect the firmware for quanton under 20150713-4b9fc7dc46 is not correct.

Thk,

Jerome

**Comment by guilhermito** [comment]
You need an updated bootloader, the flash size available for fw was changed

**Comment by JeromePilot** [comment]
Thk for your prompt reply ;o)

 

Do you have a link with the appropriate bootloader ? I cant find one even
if I follow the wiki
(https://github.com/TauLabs/TauLabs/wiki/Flashing-bootloaders)

 

Cheers and thk again

 

Jerome

 

  _____  

De : guilhermito [mailto:notifications@github.com] 
Envoyé : samedi 25 juillet 2015 01:21
À : TauLabs/TauLabs
Cc : JeromePilot
Objet : Re: [TauLabs] Can not update firmware to 20150713-4b9fc7dc46 on
Quanton (#1747)

 

You need an updated bootloader, the flash size available for fw was changed


Reply to this email directly or view
<https://github.com/TauLabs/TauLabs/issues/1747#issuecomment-124763574>  it
on GitHub.
<https://github.com/notifications/beacon/AM3Vn6a5CBa4Zvxg1sgErT4AuGAkFrxnks5
ogr_4gaJpZM4FfeQ3.gif> 



---
Ce courrier électronique ne contient aucun virus ou logiciel malveillant parce que la protection avast! Antivirus est active.
https://www.avast.com/antivirus

**Comment by Trex4Git** [comment]
I updated my bootloader on the Quanton from the GCS.

I think it was the "bu_quanton.tlfw", when I remember correctly

**Comment by JeromePilot** [comment]
Thk for your reply.

 

Update the bootloader by GCS is not working on my computer (XP may be). As
per the wiki (https://github.com/TauLabs/TauLabs/wiki/Flashing-bootloaders)
the bootloader update is by
<http://www.st.com/web/en/catalog/tools/PF258168> STM32 ST-LINK utility.

 

The files with extension .tlfw seems to be firmware. The bootloader have
extension .bin I think. If you have the latest bu_quanton.bin so I can
try.

 

Thk U

 

Jerome

 

  _____  

De : Trex4Git [mailto:notifications@github.com] 
Envoyé : samedi 25 juillet 2015 17:43
À : TauLabs/TauLabs
Cc : JeromePilot
Objet : Re: [TauLabs] Can not update firmware to 20150713-4b9fc7dc46 on
Quanton (#1747)

 

I updated my bootloader on the Quanton from the GCS.

I think it was the "bu_quanton.tlfw", when I remember correctly 


Reply to this email directly or view
<https://github.com/TauLabs/TauLabs/issues/1747#issuecomment-124854051>  it
on GitHub.
<https://github.com/notifications/beacon/AM3Vn5Gx5-7H-Kpb5Ndfs5ia4xx3k2jLks5
og6YEgaJpZM4FfeQ3.gif> 



---
Ce courrier électronique ne contient aucun virus ou logiciel malveillant parce que la protection avast! Antivirus est active.
https://www.avast.com/antivirus

**Comment by JeromePilot** [comment]
Just check, the present bootloader on my board is V81.
![erreur bootloader quanton](https://cloud.githubusercontent.com/assets/13489567/8891088/39cc7168-331a-11e5-8a2e-7df13b28c95b.JPG)

**Comment by JeromePilot** [comment]
Where can I find a newer bootloader than the V81 that is flashed on my
board. I have no linux machine where I could make it

 

Cheers

 

Jerome

 

  _____  

De : guilhermito [mailto:notifications@github.com] 
Envoyé : samedi 25 juillet 2015 01:21
À : TauLabs/TauLabs
Cc : JeromePilot
Objet : Re: [TauLabs] Can not update firmware to 20150713-4b9fc7dc46 on
Quanton (#1747)

 

You need an updated bootloader, the flash size available for fw was changed


Reply to this email directly or view
<https://github.com/TauLabs/TauLabs/issues/1747#issuecomment-124763574>  it
on GitHub.
<https://github.com/notifications/beacon/AM3Vn6a5CBa4Zvxg1sgErT4AuGAkFrxnks5
ogr_4gaJpZM4FfeQ3.gif> 



---
Ce courrier électronique ne contient aucun virus ou logiciel malveillant parce que la protection avast! Antivirus est active.
https://www.avast.com/antivirus
