### ISSUE TITLE
GCS: Crashed when chose "Antenna Track Gadget"

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#1755]
When I switch to "Edit Gadgets Mode" and chose "Antenna Track Gadget" GCS crash immediately.
OS: Windows 8.1 x64 16GB Ram

![image](https://cloud.githubusercontent.com/assets/2094549/8937533/7517975c-3559-11e5-8387-928a35d64442.png)

![image](https://cloud.githubusercontent.com/assets/2094549/8937525/66307b50-3559-11e5-8027-9fc826ffae96.png)

**Comment by peabody124** [comment]
In that case we should probably remove that gadget entirely if it is broken. It hasn't been maintained in years.

**Comment by cGiesen** [comment]
I agree. ;)
I just play around to test the GUI.

**Comment by mlyle** [comment]
Antenna track gadget removed!  Thanks for the report.
