### ISSUE TITLE
GCS Log Warning

### ISSUE THREAD

**Issue by jihlein** [TauLabs/TauLabs#1768]
What does the GCS log warning:

20:46:38[WARNING]file:///C:/TauLabs/build/ground/gcs/share/taulabs/pfd/default/PfdIndicators.qml:17:38: Unable to assign [undefined] to QString

mean?  Seeing this on latest next build, Win7 platform.

![image](https://cloud.githubusercontent.com/assets/3869782/9052150/450c2a24-3a21-11e5-8b36-fbdff0392fa1.png)

**Comment by tracernz** [comment]
The [GCSTelemetryStats.Status property](https://github.com/TauLabs/TauLabs/blob/next/ground/gcs/share/taulabs/pfd/default/PfdIndicators.qml#L17) isn't being copied into QML. It's the same bug as #1764 I think.

**Comment by tracernz** [comment]
It's been annoying me too. Would be great if you could test #1769 and confirm it's fixed.
