### ISSUE TITLE
Proposal: remove support for CC (not CC3D).

### ISSUE THREAD

**Issue by mlyle** [TauLabs/TauLabs#1772]
There are very few of the boards out there and probably none are flying.  Supporting CC uses a few bytes of CC3D memory and adds complexity in several places.

@solidgoldbomb @CheBuzz @guilhermito @elafargue @peabody124 any objections?

**Comment by DTFUHF** [comment]
This will probably ease confusion too among new TL adopters.

Is CC original even open source HW?

**Comment by mlyle** [comment]
It appears to have documents in the tree.

**Comment by tracernz** [comment]
This would make it easier to clean up the F1 ADC stuff a bit too.

**Comment by mlyle** [comment]
Also on the list: remove support for I2C PCF8591 ADC (only supported on CC flexiport, right now, and doesn't build by default).

**Comment by peabody124** [comment]
I don't love the idea if it is just to remove a few switch statements. I believe the big memory hit is the ADC FIFO which is dynamically allocated on CC (meaning it probably doesn't support autotune).

That being said, supporting pretty old hardware with unavailable sensors shouldn't block serious enhancements.

**Comment by mlyle** [comment]
So, basically, there's three reasons.  First, the way the sensors is bifurcated makes it a little more complicated to handle non-acro Naze variants in the future.  Second, tracernz is going to do some F1 ADC cleanup for battery monitoring on OpenNaze that it'd be nice to not account for primary flight sensors being on that on CC.

But the really big one is to keep the size of the test matrix sane.  If no one flies it, either it ends up untested or developers spend effort keeping something working that no one uses.  This is different from CC3D where there's a vibrant community around these targets and a large number of initial units.  The number of CC units being flown out there is possibly 0 and is certainly small and rapidly decaying.

**Comment by SystemsGuy** [comment]
It does beg the question - is anyone still flying a CC?  I've had mine in a box for at least two years...

**Comment by guilhermito** [comment]
Yes I'm still flying it, so I would prefer to continue to support it as a target

**Comment by mlyle** [comment]
OK, that's good enough for me-- at least one flying out there.  I'll try again in a couple releases ;)
