### ISSUE TITLE
Rate Pirouette Compensation

### ISSUE THREAD

**Issue by fujin** [TauLabs/TauLabs#1776]
Per the old vbar piro comp of yore, we might consider rotating the integral accumulators for pitch and yaw such that during pirouette, no extra roll is commanded. We should also make sure to _not_ do this in leveling/horizon (rate/mwrate only?) due to potentially adverse side effects.

https://youtu.be/gslSFUj6cnk
https://youtu.be/NDzKVFRrf7Q

https://www.youtube.com/watch?v=ONlgz1xK3IU (acro+ maybe not PC)

TL References:
https://github.com/TauLabs/TauLabs/blob/next/flight/Modules/Stabilization/virtualflybar.c#L75-L92

OP references: https://github.com/openpilot/OpenPilot/blob/29b9265531a808c8e337c4c9ff0091888bbd89da/flight/modules/Stabilization/innerloop.c#L325-L334
https://github.com/openpilot/OpenPilot/blob/29b9265531a808c8e337c4c9ff0091888bbd89da/shared/uavobjectdefinition/stabilizationbank.xml#L21

Implementation looks rather simple. Thoughts? :heart_eyes_cat:

**Comment by fujin** [comment]
:hear_no_evil:

**Comment by mlyle** [comment]
Do we still think this has any value?

**Comment by mlyle** [comment]
Inactive.  If shown to do something useful could be considered.
