### ISSUE TITLE
HAL Refactor/#1759 remnant: Catch when multiple ports configured for same purpose

### ISSUE THREAD

**Issue by mlyle** [TauLabs/TauLabs#1806]
E.g. GPS on main and also GPS on flexi.

**Comment by lolorc** [comment]
wbat should be the best behavior in that case ?
in the future, shouldn't it allow for 2 gps to work at the same time ?
or for quite a simpler example, what about having multiple ports getting frsky smart port output at the same time ?

**Comment by mlyle** [comment]
At first, raising an alarm that the config is no good.

Right now there's a lot of infrastructure that doesn't expect to have multiple communications targets.  Only one thread runs for these serial things and expects to speak to only a single UART/remote thing.  So there's not really a sane thing to do in general.
