### ISSUE TITLE
S.Port Telemetry not working correctly with OpenTX 2.1 

### ISSUE THREAD

**Issue by WZ9V** [TauLabs/TauLabs#1812]
The current S.Port implementation is causing duplicate entries to be created on the Taranis during discovery when using OpenTX 2.1.1 causing all telemetry slots to fill and triggering a recurring error.  My understanding is that the Teensy Mavlink converter project has similar issues with OpenTX 2.1.1

Using Taulabs - https://github.com/TauLabs/TauLabs/releases/tag/20150713 on a Sparky with X8R S.Port Telemetry connected to main port.  Sparky is only telemetry device but has an AttoPilot connected to ADC 0/1 for voltage and current measurement.

**Comment by mlyle** [comment]
@WZ9V:  Can you please try current next?  @xdandys submitted #1731 a few weeks ago for this issue.

**Comment by WZ9V** [comment]
Where would I get that one from?  I'm still pretty new to TauLabs.

**Comment by mlyle** [comment]
If you need Windows, windows builds were broken for awhile but are now available from: http://jenkins.taulabs.org/artifacts/

Note that the next branch is bleeding-edge and may have critical bugs.  It's development in preparation for the next release.

**Comment by WZ9V** [comment]
I downloaded the 8/19 Windows one from Jenkins and it did indeed fix the S.Port telemetry problem with Open TX 2.1.1 but it was a real pain getting a stable radio calibration and vehicle setup gave me manual, stabilized1 and stabilized1 for my three flight modes.  I'll start over again tomorrow and see if it acts weird again but I can at least confirm that the telemetry worked properly.  Thanks.

**Comment by mlyle** [comment]
OK.  Vehicle setup doesn't setup flight modes.  I will close this issue as it appears PR #1731 is indeed good.  Thanks for trying it out!
