### ISSUE TITLE
Auto-detection of DSMX channel resolution fails for walkera devo10 in 9-channel mode

### ISSUE THREAD

**Issue by ekaszubski** [TauLabs/TauLabs#1848]
Hardware
- 480-class collective-pitch helicopter, 120 degree swash
- sparky2
- DSMX satellite receiver (SPM9645) bound in slave or master mode, 11-bit channels, connected to sparky2 3-pin receiver header
- Walkera devo10 with deviation firmware in 9-channel DSMX mode

Issue
- auto-detection fails; DSM_RESOLUTION_MASK does not correctly detect 11-bit mode
- sparky2 falls back to 10-bit mode, which fails miserably

Solution
- force resolution to 11-bit mode in dsm_resolution (pios_dsm.c)

Extended solution
- allow user to override DSM resolution via uavobjects
- add DSMResolutionMode to manualcontrolsettings
- options are Autodetect, Force 10-bit, Force 11-bit (default Autodetect)
- I have a branch with this solution implemented and heavily tested; should I create a pull request?

**Comment by mlyle** [comment]
I like the idea of being able to force it-- please send a PR for this release.

I do think the auto-detection we have requires you to bind using sparky-- usually 4 pulses I think (it's actually 5 pulses but one pulse comes from it floating high in the bootloader :/ )

As to the other PRs-- really neat stuff.  I think they need a little more discussion.  We are coming up to a release though ( https://github.com/TauLabs/TauLabs/wiki/Endomorphism-(September)-release ) and have crossed the deadline for high risk PRs to be opened.  We've also incurred more risk than I'd like in general so it will probably be a small amount of time before these ideas can really be reviewed and commented upon.
