### ISSUE TITLE
Implement and test fastheap support on F4

### ISSUE THREAD

**Issue by BrainFPV** [TauLabs/TauLabs#1865]
Opening this issue so it doesn't get forgotten. There have been several attempts to add fast heap support, but it keeps crashing on some targets.

Original PR: TauLabs/TauLabs#1691
Take 2 PR: TauLabs/TauLabs#1822 reverted in TauLabs/TauLabs#1855

The idea is to first identify what brings most memory savings and then enable fat heap for a small number of buffers.

**Comment by mlyle** [comment]
Note we're not positive fastheap was guilty this time around.

**Comment by tracernz** [comment]
Can be closed. Fixed in #1939.
