### ISSUE TITLE
UAVObjectGenerator: no length info for options field

### ISSUE THREAD

**Issue by ekaszubski** [TauLabs/TauLabs#1886]
- Generated UAVOs have no \#define or enum element for the length of `options` fields (this info *is* generated for `elementnames`)
- Options fields are often used in case statements, but the preference is for an exhaustive list with no default, which implies a range check on the options field
- Without any length information, this range check is conditional on the last enum element; if another option is added to the end of the options list (and thus the enum), any existing range checks become invalid

**Comment by peabody124** [comment]
That should be straightforward to add and you are right. As @kubark42 comment in #1887 points out you can always cast a constant to the enum type and pass it into a method, creating an invalid value. Avoiding a default case to have the benefit of a compiler check we handle all conditions means that we don't do anything explicit in this case ...
