### ISSUE TITLE
Jenkins: Linux i686 artifacts missing GCS

### ISSUE THREAD

**Issue by tracernz** [TauLabs/TauLabs#1910]
Something must have broken because there is a 2014 build which contains GCS in the artifacts directory: http://jenkins.taulabs.org/artifacts/

**Comment by tracernz** [comment]
@lilvinz Can you please take a look at this? :)

**Comment by mlyle** [comment]
Possible we could drop i686 bins from release, I know it's been considered before..

**Comment by lilvinz** [comment]
The builder was missing QT 5.5.0. Expect a new build in an hour or so.

**Comment by mlyle** [comment]
Cool!

**Comment by mlyle** [comment]
Indeed there is bigger build output-- yay.  I (or someone else) need to test the output and we can close this.

**Comment by mlyle** [comment]
Looks good.

**Comment by tracernz** [comment]
Thanks @lilvinz, much appreciated. :)
