### ISSUE TITLE
Jenkins: All artifacts missing AQ32 and Naze firmware

### ISSUE THREAD

**Issue by tracernz** [TauLabs/TauLabs#1911]
I guess Jenkins must be using a custom command to gather up and zip the artifacts? It might be a good idea to use a standard make target so we can maintain it more easily (add a suitable one if required). In any case can we get these added please?

**Comment by tracernz** [comment]
@lilvinz Can you please take a look at this? :)

**Comment by mlyle** [comment]
Looks like the aq32/naze firmware blobs are still missing.  This is the last thing blocking a snapshot build of the next release.

**Comment by lilvinz** [comment]
I have added aq32 and naze32 to the build scripts. A build of next is in progress.

**Comment by lilvinz** [comment]
@tracernz You can open another issue for getting rid of the jenkins packaging scripts by adding a new or modifying an existing make target for that purpose.

**Comment by tracernz** [comment]
Thanks @lilvinz ! :-)
