### ISSUE TITLE
Problem with axis reverse code in MPU6K driver

### ISSUE THREAD

**Issue by AlessioMorale** [TauLabs/TauLabs#1923]
There is a problem within the code that invert mpu6000 axis to adapt them to board convention.
it is done as 
axis = - (int16_t)original value;
this create a problems as INT16_MIN != - INT16_MAX
`(int16_t)0x8000 = -32767`

`(int16_t)0x8001 = -32768`
when inverted they turns into:
` - (int16_t)0x8000 =  32767`

` - (int16_t)0x8001 = -32768`

**Comment by kubark42** [comment]
Oooh, that's a nasty one! We should check that this is restricted to only the mpu6000.

I see how you resolved it for https://github.com/librepilot/LibrePilot/blob/next/flight/pios/common/pios_mpu6000.c#L580. Would you still recommend this approach, or in the meantime has a better solution presented itself?

**Comment by mlyle** [comment]
Yes, this is high severity.

**Comment by mlyle** [comment]
I don't think we can ship with something like this known.

**Comment by mlyle** [comment]
(I'm in favor of the -1 hack, but it's unfortunate we even treat these as signed quantities given that we need to find/apply an offset later anyways.)

**Comment by AlessioMorale** [comment]
This is still fine. being a "digital" sensor 1 lsb does not make a lot of difference

**Comment by Trex4Git** [comment]
In "axis = - (int16_t)original value;" in Taulabs "axis" is a float variable; I am not sure when  the conversion to float does happen. 
Maybe a more explicit "axis = - 1.0f *  (int16_t)original value;" might work, as I think the multiplication of a float and an int should be a float ?

**Comment by kubark42** [comment]
> Maybe a more explicit "axis = - 1.0f * (int16_t)original value;" might work, as I think the multiplication of a float and an int should be a float ?

Yes, that is a very effective guard against a potential problem.

**Comment by mlyle** [comment]
I will try to read the code and look at the types of all this stuff later tonight and open a PR.
