### ISSUE TITLE
Sparky2: Main Port tx hw inverter for S.PORT telemetry

### ISSUE THREAD

**Issue by fujin** [TauLabs/TauLabs#1954]
I see the s2 has an inverter on the rxport (great!). Is it only on the rxport port? is it possible to invert outbound s.port telemetry via any of the other ports?

https://github.com/TauLabs/TauLabs/wiki/User-Guide:-FrSKY-S.PORT-telemetry this document says an external inverter is required, which will not impossible to build, doesn't work out of the box / 1wire. :)

please close if not possible, thanks! :dancer:

**Comment by mlyle** [comment]
It has an XOR on the output of rcvrport for inversion.  There's no input inverters /XOR on any ports.  Only option would be software uart which really sucks to do.
