### ISSUE TITLE
how to build a gcs release

### ISSUE THREAD

**Issue by wangzhenxing** [TauLabs/TauLabs#1957]
environment : windows7
I just run command "make gcs", copy "build/ground/gcs/" to new windows PC, run "build/ground/gcs/bin/taulabsgcs.exe". There is an error : lost Qt5Cored.dll.
I think it depends on qt environment.
@mlyle Is there any way to build a gcs release version ? or installable release version?
thanks

**Comment by mlyle** [comment]
make standalone

or follow the directions to install nsis and then make package

**Comment by wangzhenxing** [comment]
success, thanks
by the way, where can i get all the make params like : make all , make gcs, make standalone etc ?

**Comment by tracernz** [comment]
Just run make with no target, it will give you descriptions of each target.

**Comment by wangzhenxing** [comment]
run command "make"
it shows :
 mingw32-make: *** No targets specified and no makefile found. Stop.

**Comment by mlyle** [comment]
In the taulabs source directory. :P

**Comment by wangzhenxing** [comment]
it shows:

sh:C:\Program: No such file or directory
makefile:125; recipe for target 'help' failed
mingw32-make: *** [help] Error 127

but in makefile file,  i get all command

**Comment by mlyle** [comment]
GNU Make does not support paths with spaces in them.  A development source tree probably doesn't belong in C:\Program Files, either.

http://savannah.gnu.org/bugs/?712

**Comment by wangzhenxing** [comment]
resolved, thanks @mlyle 

move git from C:\Program Files(x86)\Git  to C:\Git

**Comment by wangzhenxing** [comment]
and thanks @tracernz

**Comment by wangzhenxing** [comment]
there is a new error by running command "make package"

!insertmacro: macro named "MUI_UNFUNCTION_DESCRIPTION_BEGIN" not found!
Error in script "f:/taulabs_branch_20150919_1/package/winx86/taulabs.nsi" on lin
e 364 -- aborting creation process
Makefile.winx86:17: recipe for target 'win_package' failed
mingw32-make[1]: *** [win_package] Error 1
makefile:1017: recipe for target 'package' failed
mingw32-make: *** [package] Error 2


is there any thing i must to config? @mlyle

**Comment by guilhermito** [comment]
Please move this convo to the forum

**Comment by wangzhenxing** [comment]
the forum is inactivity
no one reply

**Comment by wangzhenxing** [comment]
I have got a plan, delete line 364 ~ 368 (drop uninstall function). And run command "make package", it works
