### ISSUE TITLE
MPU6000 temperature calibration is incorrect

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#1958]
@AlessioMorale discovered this: https://bitbucket.org/librepilot/librepilot/pull-requests/45/lp-108-fix-temp-calculation-get-rid-of/diff

We suffer from it as well: 
* https://github.com/TauLabs/TauLabs/blob/next/flight/PiOS/Common/pios_mpu6000.c#L671
* https://github.com/TauLabs/TauLabs/blob/next/flight/PiOS/Common/pios_mpu6050.c#L704

From the MPU-6000 register map: 
> The temperature in degrees C for a given register value may be computed as:
```Temperature in degrees C = (TEMP_OUT Register Value as a signed quantity)/340 + 36.53```

**Comment by mlyle** [comment]
To confirm, this isn't a correctness issue, but instead an ISR performance issue?  It looks like we set the registers to the right setting in flight/PiOS/STM32F4xx/startup.c:75 to preserve state.  (per http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0298a/index.html )

**Comment by mlyle** [comment]
@Trex4Git this may relate to your observed CPU utilization differences between mpu6000 and mpu9250 at high sample rates.

**Comment by mlyle** [comment]
Wait, in our code it doesn't even happen in the ISR.  I think this is a non-issue for us.

**Comment by kubark42** [comment]
The constant is wrong. We use 35.0.

În data de miercuri, 23 septembrie 2015, Michael Lyle <
notifications@github.com> a scris:

> Wait, in our code it doesn't even happen in the ISR. I think this is a
> non-issue for us.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TauLabs/TauLabs/issues/1958#issuecomment-142762020>.
>


-- 
Sent from my Banana Phone.

**Comment by mlyle** [comment]
> Temperature in degrees C = (TEMP_OUT Register Value as a signed quantity)/340 + 36.53

vs

> 35 + (x+512)/340

are equivalent functions. 

Librepilot didn't change the function, they removed floating point.

**Comment by AlessioMorale** [comment]
Sorry for the confusion, the main point of LP-108 is to remove the last, unneeded, floating point operation from the ISR. 
That part about the calculation was just a late night-induced brain fart :) then it was left like this for readability.

**Comment by kubark42** [comment]
<facepalm>

I just noticed the constant in the math was different, I should have caught
that a component moved to inside the parentheses.

În data de joi, 24 septembrie 2015, AlessioMorale <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a scris:

> Sorry for the confusion, the main point of LP-108 is to remove the last,
> unneeded, floating point operation from the ISR.
> That part about the calculation was just a late night-induced brain fart
> :) then it was left like this for readability.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TauLabs/TauLabs/issues/1958#issuecomment-142837124>.
>


-- 
Sent from my Banana Phone.

**Comment by mlyle** [comment]
:) It happens, assuming OK to close.
