### ISSUE TITLE
Ensure that defaultname in UAVO is present in list of options

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#2080]
E.g., ```<field name="FirstMotorSense" units="" type="enum" elements="1" options="CW,CCW" defaultvalue="None"/>``` passes the generator just fine. The generator should catch this and fail.

**Comment by tracernz** [comment]
This is a little difficult to do with the new inheritance system introduced with HAL as the field parents are not resolved in the parser. We don't know what the options are for inherited fields who don't specify their own options, e.g. https://github.com/TauLabs/TauLabs/blob/next/shared/uavobjectdefinition/hwaq32.xml#L108.

**Comment by mlyle** [comment]
Could easily be done at resolveParents time

**Comment by tracernz** [comment]
True @icee. I managed to have a battle with whitespace :<, ended up cleaning up the whole file inadvertently.
