### ISSUE TITLE
ChibiOS NIL port?

### ISSUE THREAD

**Issue by beriberikix** [TauLabs/TauLabs#2099]
Has anyone attempted to port TL to use [NIL](http://chibios.org/dokuwiki/doku.php?id=chibios:product:nil:start), from ChibiOS? It is smaller and uses less resources, though has [less features](http://chibios.org/dokuwiki/doku.php?id=chibios:articles:rt_vs_nil) than the full RTOS. As long as TL doesn't use some of the more advanced features of the RTOS, it should be do-able.

My end-goal is to get TL running on [Cheerson CX-10](http://www.eevblog.com/forum/reviews/teardown-cheerson-cx10-mini-quadcopter/).

**Comment by tracernz** [comment]
It doesn't have mutexes, queues or dynamic memory, not going to be easy since those are all used extensively throughout the firmware.

**Comment by beriberikix** [comment]
Shucks, figure that might have been the case :/

**Comment by mluessi** [comment]
Closing this, as NIL doesn't have the features we need.
