### ISSUE TITLE
Objects not saved FlightBatterySettings

### ISSUE THREAD

**Issue by HenryLeinen** [TauLabs/TauLabs#2215]
I am using a Quanton board with the latest software (Nov. 2015).
I activate the "Battery Monitoring" Module --> it works in general.

However, whenever I try to change any of the parameters (e.g. the number of cells or the battery capacity) and click on SAVE, I get a negative feedback and in the log it says :
20:37:03[DEBUG][smartsavebutton.cpp] Sending object to remote end -  "ModuleSettings"
20:37:03[DEBUG][smartsavebutton.cpp] Save request for object "ModuleSettings"
20:37:03[DEBUG][smartsavebutton.cpp] Sending object to remote end -  "FlightBatterySettings"
20:37:03[DEBUG][smartsavebutton.cpp] Save request for object "FlightBatterySettings"
20:37:03[DEBUG][smartsavebutton.cpp] failed to save: "FlightBatterySettings"
20:37:03[DEBUG][smartsavebutton.cpp] Error, tried to apply/save a non-settings object
20:37:03[DEBUG][smartsavebutton.cpp] Sending object to remote end -  "PicoCSettings"
20:37:03[DEBUG][smartsavebutton.cpp] Save request for object "PicoCSettings"
20:37:04[DEBUG]RESULT "Objects not saved:\nFlightBatterySettings\n" () ("FlightBatterySettings") ()

~LeiHen();

**Comment by peabody124** [comment]
You try power cycling after enabling the module

**Comment by HenryLeinen** [comment]
That does not work. Tried it several times. It always gives the same error. After power cycling, the same 'initial' values reappear.

**Comment by kubark42** [comment]
@HenryLeinen Is it possible you have a firmware/GCS version mismatch? That would explain this error.

**Comment by HenryLeinen** [comment]
I checked it, but firmware and GCS are matching (both are on 20151123).

**Comment by HenryLeinen** [comment]
I have deleted the settings partition, reconfigured everything and now it works. I have double checked on my other quanton board. Everything works. I think we can close this issue.
