### ISSUE TITLE
PWM outputs mapping on AQ32 boards

### ISSUE THREAD

**Issue by adorus** [TauLabs/TauLabs#2227]
Motor 3 should be on PC7; currently mapped to PA15.
Motor 4 should be on PC6; currently mapped to PB3.

**Comment by jihlein** [comment]
No, this mapping was intentional.  It frees up PC6 and PC7 for use as UART6.  There are quite a few differences in how the IO pins are used on the AQ32 Taulabs software vs the standard AQ32 software.  See the aq32Taulabs.xlsx file in the AQ32 target hardware folder.

**Comment by kubark42** [comment]
@adorus Do you consider this resolved? If so, can you close the issue?

**Comment by tracernz** [comment]
Maybe document on the wiki rather than just in the source tree.
