### ISSUE TITLE
PPM not working on Brushed Sparky

### ISSUE THREAD

**Issue by Swirklich** [TauLabs/TauLabs#2238]
Tried two different d4r-ii RXs in PPM mode (signal pin 3 + 4 bridged) that I swapped back and forth between another quad (works fine) and the Brushed Sparky (doesn't work at al). d4r-ii is bound to my Taranis (solide green light), but like I said: the same RXs work on my other (non-TauLabs) boards.

Used a multimeter to check continuity between Signal from the RX  through the RCVR port and the CPU (all pass). 
Tried the former and latest Brushed Sparkt configuration files from GitHub. In GCS, the PPM signal isn't picked up at all. Hardware -> RCVR is set to PPM. Power-cycled multiple times, settings appear to be saved (didn't default to Disabled). I also verified this under ReceiverActivity. Neither the wizard nor manual configuration pick up anything.

**Comment by Swirklich** [comment]
As mentioned by another user: 

_I had similar issues but with a MicroFrX. It seems like mine were caused by the combination of a series resistor in my receiver and the pull-down resistor on the Brushed Sparky interacting to cause the PPM signal to be attenuated too far. If you have a scope, try to probe the PPM output from your receiver when it's not plugged in to the brushed sparky, and when it is. If you see the PPM signal clearly when it is not plugged in, but it gets squished down when it's plugged in to the Sparky, you have the same issue as I did. My fix was to remove the 10k pull-down resistor on the Brushed Sparky._

I hope we can work around that resistor, as it would be a real pain for every PPM user to remove a tiny resistor on the PCB (this could go wrong in so many awful ways with untrained hands).

**Comment by peabody124** [comment]
I wasn't able to replicate your issue. Using next PPM input works on my BrushedSparky:

![screen shot 2016-04-02 at 5 53 19 pm](https://cloud.githubusercontent.com/assets/618346/14229564/22008a12-f8fc-11e5-978c-71bc17ef2b5e.png)

Here is the configuration:
![screen shot 2016-04-02 at 5 56 19 pm](https://cloud.githubusercontent.com/assets/618346/14229574/403b9a8a-f8fc-11e5-85ba-90aad5c1462c.png)

This is my connection:
![20160402_175339](https://cloud.githubusercontent.com/assets/618346/14229576/579ac3b8-f8fc-11e5-8b07-f0e76bf98c5c.jpg)

**Comment by Swirklich** [comment]
Thanks Peabody, is there anything else I can try? I have been wrecking my head around this for a week now, trying different d4r-ii's... What am I missing?

**Comment by Swirklich** [comment]
Thanks for taking the time, Peabody. I am out of ideas. You said you've had your d4r-ii for a while now. I know they changed their firmware a couple of times over the past year or so on the RX and this one is only a few weeks old. I can't be positive this _is_ the reason, but we've pretty much excluded everything else by now. 
**Could you do me one last favor please and point me towards the 10k pull-down resistor on the below schematic** (see my 2nd post above):

![download 2](https://cloud.githubusercontent.com/assets/18214050/14230003/6e3afec6-f947-11e5-8cbb-28e7bffa2fe9.png)

Another user had these same issues not too long ago, also with a FrSky RX, and I am willing to try the same if know which one it is exactly.

**Comment by Swirklich** [comment]
Flashed Raceflight, everything functioning but PPM input. Peabody, I think you can save yourself the trouble of trying latest current release. This _must_ be hardware.

**Please help me locating 10k pull-down resistor on Signal so I can remove it and see if this resolves issue!**

**Comment by peabody124** [comment]
![screen shot 2016-04-03 at 8 19 48 pm](https://cloud.githubusercontent.com/assets/618346/14236348/9021c866-f9d9-11e5-8374-27b318130f23.png)

Here it is. If you have verified the continuity between the receiver pin and the MCU that would be the only hardware error I could imagine that would cause this. I'm skeptical the resistor is the problem, but possibly it is. Sounds like I'm using the same receiver you are.

**Comment by Swirklich** [comment]
I think I just got unlucky and received a dud. Removing the resistor didn't change anything. Oh well, sorry for wasting your time mate!

**Comment by JR63** [comment]
from peabody124: "that would be the only hardware error I could imagine that would cause this"

There could be another hardware error: If the MOSFET (Q7A) is defective (gate - source shorted) it could result in pulling the PPM signal down.

Try to desolder the Q7 and give it a try ;-)

**Comment by Swirklich** [comment]
JR63, thanks a lot man. That did it indeed! You raaawk :). Let's if everything else behaves normal now!

**Comment by JR63** [comment]
:-)

**Comment by peabody124** [comment]
Great catch!!! Let me check the code and verify the gate input is actively driven in all cases.

**Comment by Swirklich** [comment]
Unfortunately, PPM was erratic and all over the place, Sparky was uncontrollable. Tried a second brand-new d4r-I. 
Today, while doing some tests, my Brushed Sparky finally gave up the ghost and let go of the magic smoke when I plugged in the battery once more. No idea what happened. Which means that, for better or worse, I am out of the game for good now.

**Comment by JR63** [comment]
Bad news :-(
