### ISSUE TITLE
Brushed Sparky 2 Solder battery directly

### ISSUE THREAD

**Issue by brendabrandy** [TauLabs/TauLabs#2246]
I am building the brushed sparky 2 right now and I was wondering whether I can solder the 1S battery to the quadcopter directly without the connectors. If I can do so, where can I charge the battery?

Thanks!!

**Comment by peabody124** [comment]
No, for exactly that reason. You need to be able to disconnect the battery
and charge it. Leaving it connected would destroy the battery.
