### ISSUE TITLE
"recipe for target 'uavobjgenerator' failed" Error 127

### ISSUE THREAD

**Issue by ghost** [TauLabs/TauLabs#2247]
`make all` gives this error:

``` bash
*NOTE*   Sanitized disallowed variable 'TMPDIR' from environment
/usr/bin/sh: line 1: qmake: command not found
makefile:317: recipe for target 'uavobjgenerator' failed
mingw32-make: *** [uavobjgenerator] Error 127
```

**Comment by peabody124** [comment]
Run '''make qt_sdk_install'''

**Comment by ghost** [comment]
I guess something very essential is missing. "make qt_sdk_install" gave the same error.

``` bash
*NOTE*  Sanitized disallowed variable 'TMPDIR' from environment
/usr/bin/sh: wget: command not found
C:/Users/mettinoktay/taulabs/make/tools.mk:87: recipe for target 'qt_sdk_install' failed
mingw32-make: *** [qt_sdk_install] Error 127`
```

**Comment by mlyle** [comment]
Follow this development setup procedure:  https://dronin.readme.io/docs/development-setup-windows

This documentation is for dRonin, but it's very similar to the procedure for Tau Labs.

Note that on Windows neither project automatically installs the Qt environment.  Also note that I think Tau Labs uses an older Qt).

**Comment by peabody124** [comment]
For Tau Labs you might want to look at this https://github.com/TauLabs/TauLabs/wiki/Development-Windows-setup

**Comment by tracernz** [comment]
The Tau qt_sdk_install target doesn't work because it depends on wget and that isn't included in git for windows anymore. Change the wget line in make/tools.mk for curl and it will work. See here for example: https://github.com/d-ronin/dRonin/commit/fad0e8ed3eb7828b55b3de21b1f505699fe62690

**Comment by ghost** [comment]
Hey guys I switched to Ubuntu and everything compiles now.
