### ISSUE TITLE
Sparky2: PWM out/in simultaneous

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#2259]
Add support to Sparky2 for the 6th PWM output to become a PWM/PPM input. This will allow receiving the RSSI signal from something like an SBus receiver.

Side note, I'm surprised the RSSI is not available in the SBus data stream.

**Comment by peabody124** [comment]
Workaround: https://oscarliang.com/rssi-ppm-channel-taranis/ shows how to use the Taranis to echo the RSSI signal from telemetry back out to a particular channel

**Comment by tracernz** [comment]
> Side note, I'm surprised the RSSI is not available in the SBus data stream.

Seems to be common to most brands, quite weird. I asked Jeti about it and they said they didn't do it because there's no standardised way to output RSSI... That didn't really make a lot of sense to me since they're using their own protocol.

**Comment by peabody124** [comment]
@tracernz do you mean you have you seen anything suggesting it is available in an SBus stream, and only some brands don't have it?

**Comment by tracernz** [comment]
No, by brand I meant first-party vendors like Futaba, Spektrum, Jeti who define the various protocols. :wink:

**Comment by peabody124** [comment]
Ok. I'm going to actually close this as won't fix. Turns out the RSSI signal isn't a sensible PWM signal. You can either analog LPF it, or have the Taranis relay it as a looped-back channel and then import it from the SBus/PPM stream. I opted for that (although the failsafe behavior is a bit jerky and drives it to a nuts value, so it's still clear you lost signal)
