### ISSUE TITLE
Automatically generate uavobjects.pro and UAVObjects.inc

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#231]
These files have large parts that are nothing more than a list of all available UAVOs on the system. GCS will fail to compile if the uavobjects.pro list does not match the list of available UAVOs, so there doesn't seem much reason not to automatically generate the list

The firmware fails a little more gracefully, but it's still a extra work to have to add new UAVOs to the list in each UAVObjects.inc, and as we add more boards this work will grow in size. (A new UAVO already requires modifying eight files if it is to be added to all flight boards.) The downside of automatically adding all UAVOs might be that there cases where we don't want to list them all of them. Are there?

**Comment by mlyle** [comment]
My plan is:

GCS builds with all UAVOs programmatically.

UAVOs are broken into two lists:  

* UAVOs that are present on all boards
* Of other UAVOs, UAVOs that are present on all larger (non-SMALLF1 boards).

Then F1 makefiles include the first list; big makefiles include both lists; and each makefile can add any target-specific ones that apply.

**Comment by mlyle** [comment]
#1759 causes GCS to automatically pick up UAVO list.  Still need to do the flight side.

**Comment by mlyle** [comment]
Merged and done.
