### ISSUE TITLE
Rewrite control gadget with native joystick HID support

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#323]
This could drop the requirement of SDL

**Comment by mlyle** [comment]
While requiring SDL kinda sucks, I'd say we should close this.  1) it's not a priority, 2) using someone else's abstraction/the system joystick drivers is good.  Otherwise you need to calibrate sticks, etc, all over again.

**Comment by mlyle** [comment]
(Closing in 1 week if no comment).
