### ISSUE TITLE
Windows Development Environment Setup Wiki

### ISSUE THREAD

**Issue by Felkk** [TauLabs/TauLabs#332]
The windows environment setup wiki page https://github.com/TauLabs/TauLabs/wiki/windows  needs to be cleaned up so new developers can get up and running on windows. It appears that there are conflicting instructions and confusion over what exactly to download (especially for Qt).

**Comment by mlyle** [comment]
https://github.com/TauLabs/TauLabs/wiki/Development-Windows-setup   is the current one, it's correct though a little messy.  Closing old issue.
