### ISSUE TITLE
Move QML PFD files to appropriate location.

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#460]
As raised by @peabody124 in https://github.com/TauLabs/TauLabs/pull/458, the QML files relating to the PFD should not be in the share directory. "In principle those [shared files] were "replaceable" components of the widgets - e.g. artwork that was selected at run time."

The proposed solution is to move them to the appropriate location in plugins/pfdqml.

**Comment by mlyle** [comment]
WONTFIX
