### ISSUE TITLE
FlyingF3 different shield handling.

### ISSUE THREAD

**Issue by guilhermito** [TauLabs/TauLabs#535]
Currently we have a hwflyingf3 UAVO, however since we have different shields making each one a different combination of hardware we need a way to distinguish them to allow proper hardware initialization.
Proposed solution is to create and use a "shields" field on the hwflyingf3 UAVO and use it to properly init the hw.

**Comment by mlyle** [comment]
Is this still relevant/useful?  A lot fewer people are building flyingf3's now and there's not shields out there.. and anyone who has one has it working.

**Comment by mlyle** [comment]
Closing-  likely WONTFIX because of 2 years of inactivity and less activity on flyingf3/shields.
