### ISSUE TITLE
I2C Init can lock up

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#562]
If the pin is shorted to ground the I2C_Init method locks up since there are various while loops in the reset bus function.

We should probably add a timer that when it expires there is a failure.  However, the method doesn't return an error code so we probably needs to add another event and an error state?  Then it can be checked by PIOS_Init and not enable the IRQ handler.

Thoughts, @solidgoldbomb  ?

**Comment by mlyle** [comment]
Fixed for F3 and F4 by #1728

**Comment by mlyle** [comment]
There also appears to be appropriate F1 logic to deal with retry counters.  Closing.
