### ISSUE TITLE
Drivers should use cmsis __REV16 for reversing endianess

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#598]
For the sensor drivers we should consider using the __REV16 instruction where we reverse the byte order for each sensor channel (in the mpu9150/mpu6050/mpu6000 drivers).  One issue with this is that in PiOS/Common the code right now should be portable to any PiOS implementation but this would restrict it to ones using CMSIS.  However, given that is all we intend to use for the forseable future it might be worthwhile.

It's worth emphasizing this is called very very frequently so optimization is worthwhile.

**Comment by mlyle** [comment]
Looks like what we do now is:

```
 2ee:   f89d 3005       ldrb.w  r3, [sp, #5]
 2f2:   900a            str     r0, [sp, #40]   ; 0x28
 2f4:   f89d 0004       ldrb.w  r0, [sp, #4]
 2f8:   ea43 2000       orr.w   r0, r3, r0, lsl #8
 2fc:   b200            sxth    r0, r0
 2fe:   f7ff fffe       bl      0 <__aeabi_i2f>
```

Which isn't awesome-- you can save 2 cycles.  On the other hand, it's followed by a integer to float conversion and a floating point multiply which is hundreds of cycles on these targets, so this isn't even worth a percent of the runtime of the routine it's in.  Closing.
