### ISSUE TITLE
[GCS] does not working properly on windows 8

### ISSUE THREAD

**Issue by JamesxL** [TauLabs/TauLabs#616]
OS: windows 8 pro 64bit
GCS ver: 20130608
FW ver: sparky, next, 2013-06-03
GCS is not installed in system folder

Problem:

1. in system tab, after change any system setting (from drop down list). the upload and save button keep grey, unable to save change. 
in another word, "request", "send", "load", "save", "erase" are grey all the time under any condition.

2. in scope tab, no graph is plotted. all charts are blank.

**Comment by mlyle** [comment]
I have Windows 8.1, works fine for me-- super slow but works fine.  

@JamesxL does this still happen for you?  I wonder if it relates to using a Chinese edition of Windows.

Without further details we'll have to close.

**Comment by mlyle** [comment]
Closed-- WORKSFORME/no further details.
