### ISSUE TITLE
Next sim_posix_revolution borked

### ISSUE THREAD

**Issue by rghunter** [TauLabs/TauLabs#622]
I get the following when trying to run sim_posix_revolution (as compiled from next): 

Running as PID: 32403
Timer Resolution for Run TimeStats is 100 ticks per second.
Unable to initialize flash ut simulator: -1
sim_posix_revolution.elf: /home/rhunter/git/taulabs/flight/PiOS.posix/posix/../../tests/logfs/pios_flash_ut.c:79: PIOS_Flash_UT_StartTransaction: Assertion `!flash_dev->transaction_in_progress' failed.
Aborted (core dumped)

**Comment by mlyle** [comment]
Simulator now creates theflash.bin automatically, and there are appropriate wiki instructions for simulator setup.
