### ISSUE TITLE
Does MavlinkBridge work on CC?

### ISSUE THREAD

**Issue by guilhermito** [TauLabs/TauLabs#633]
Recently there was an increase in stack usage making the available stack for modules much less than it used to be.
The MavLinkBridge for example is now impossible to work on CopterControl since it requires about 600 bytes (probably more now with Vinz recent changes) and the stack available is about 400 bytes.
I don't know enough about the memory management to pinpoint where the stack usage increased but buy reverting to other revisions I think it was around the FreeRTOS upgrade. The reason I was not able to exactly pinpoint the revision will be discussed in another issue.

**Comment by mlyle** [comment]
Need to see if mavlinkbridge works on CC.

**Comment by SystemsGuy** [comment]
Tested on CC3D with mlyle's 20150813 build with no issues.  Even flys :)

**Comment by SystemsGuy** [comment]
![tau labs gcs_2015-08-13_18-18-03-cc3d](https://cloud.githubusercontent.com/assets/2819484/9264019/ee1fc77e-41e7-11e5-919a-e784b4f75571.jpg)

**Comment by SystemsGuy** [comment]
![tau labs gcs_2015-08-13_18-37-05-ss](https://cloud.githubusercontent.com/assets/2819484/9264297/605f9754-41ea-11e5-88ed-179e92bebb76.jpg)

**Comment by mlyle** [comment]
Fixed by #1797.
