### ISSUE TITLE
tcsetattr does not timeout

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#656]
In QextSerialPort::close(), ```tcsetattr(fd, TCSAFLUSH | TCSANOW, &old_termios);``` does not timeout, which leads to a close serial port operation indefinitely freezing GCS.

QExtSerialport has been updated in 2012, perhaps we should update our copy, which could date from 2007. https://code.google.com/p/qextserialport/downloads/list?can=1&q=

**Comment by mlyle** [comment]
We no longer use qextserialport.  Closing.
