### ISSUE TITLE
Raw ADC values in uavo

### ISSUE THREAD

**Issue by KipK** [TauLabs/TauLabs#702]
Hi

Would be nice to have acccess to all ADC values through UAVO and not only current & voltage ones.

Could be used easily for analog RSSI on osd or groundstation, but probably usefull to stay generic for other uses.

Having an analog rssi deddicated object like current & sensor would be bonus for native Mavlink osd.

**Comment by kubark42** [comment]
Closing this because the architecture has changed and there are currently no ADC values directly available through UAVOs. RSSI, for instance, is now part of ManualControlCommand.
