### ISSUE TITLE
[sparky] althold and pathplanner+pathfollower cause memory error

### ISSUE THREAD

**Issue by JamesxL** [TauLabs/TauLabs#737]
board sparky. fresh only connected to usb

commit hash, eceab62e

reproduce method.

enable altitude hold module
enable pathplanner
enable vtolpathfollower

power cycle

memory error (block red)..

---
the issue occurs randomly on power cycle. 

--
disable alt hold would removed the problem.

--

**Comment by mlyle** [comment]
Would be nice to hit this in test for endo release.

**Comment by peabody124** [comment]
This issue is pretty old. Is it still valid?

**Comment by mlyle** [comment]
That's why I said retest would be nice.

**Comment by peabody124** [comment]
Ah I didn't understand what hit this in test meant. My bad.

**Comment by mlyle** [comment]
Still need to test this...

**Comment by peabody124** [comment]
Sorry I just fully read this. This is a known issue and not something I think is fixable on Sparky1. That is just too many modules. This probably shouldn't be tagged as endo. It can probably be closed as a won't/can't fix.

**Comment by mlyle** [comment]
I'd like sparky1 to follow waypoints.  We'll see if it can run now and if not how close it is.  Still haven't gotten to it.

**Comment by mlyle** [comment]
Note something being tagged for the release doesn't mean it is going to be fixed in the release, just that it  has some kind of pending action before the release, even if that action is "watch and wait" or "cover in test".

**Comment by mlyle** [comment]
Sparky/PPM/GPS/AltHold/VtolPathFollower/PathPlanner = 1304 bytes free heap.  WORKSFORME.

Preprogrammed path "logo" yield 968 bytes.

Who needs a fancy F4 anyways? ;)

**Comment by kubark42** [comment]
Great! 

P.S. AltitudeHold shouldn't even be necessary for a path planner flight.

**Comment by mlyle** [comment]
Nope, but if you expect to fly poshold you probably want to fly althold too sometimes (maybe less so now with zippyloiter).
