### ISSUE TITLE
RFC: Refactor ManualControlCommand to ControlCommand and ManualInput

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#743]
With the new control structure, as designed by @peabody124, we can formalize the separation between command inputs, and begin to grow the types of commands we can automate.

With the proposed refactoring, the advantage is that ControlCommand can include open-loop control inputs (throttle, collective, flaps, spoilers, trigger mechanisms), without needlessly complicating the stabilization module. For example, a mission director can cleanly write control commands without mixing them with input pulse widths.

I don't believe this should change much in the way the ManualControl module works. It would finish the formal separation between the various input controllers (geo-fence, failsafe, tablet, and manual) at the cost of some RAM. I think the improved architecture makes it worth it.

ManualControlCommand UAVO would split into ControlCommand and ManualInput. ManualInput would store the PWM input widths, which would be processed by the MaualControl module. This is identical to how the ManualControl module currently works.

The ManualControl module would digest all incoming control inputs and write them to a ControlCommand UAVO. Part of this UAVO would be pushed to StabilizationDesired, as a function of the control commands. Similar to how is currently done, the ControlCommand fields would be mapped between -1 and 1; whereas the StabilizationDesired fields would stay the same, with the exception of Throttle (see below).

The Stabilization module would only change one line of code, which is the passthrough for the throttle. StabilizationDesired currently includes throttle, which isn't correct. Throttle is an open-loop control input, not a state value. StabilizationDesired should contain only state output variables that can be stabilized.

The Actuator module would read both ActuatorDesired and ControlCommand. This is similar to how the Actuator module currently reads both ActuatorDesired and AccessoryDesired. Here is where the Stabilization throttle passthrough would be replaced by a direct reading of the throttle ControlCommand field. Likewise, at the same time all other control inputs would be passed through to their respective actuators.

**Comment by mlyle** [comment]
Close- dead RFC
