### ISSUE TITLE
Failsafe still broken

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#761]
Failsafe is still broken for HiTL and fixed-wing. This is still causing issues after several months, so we might want to consider removing if the pre-existing functionality can't be rapidly restored.

#### HiTL
HiTL problems are documented in https://github.com/TauLabs/TauLabs/issues/508, so there's no need to repeat them here.

#### Fixed-wing
Fixed-wing problems come from:
1) Setting yaw to AxisLock. First, this is actively bad for fixed-wing flight, as it causes cross-control which can lead to a spin. Second, fixed-wing UAVs can be* flown with CoordinatedFlight mode, which has gains approximately 100 times higher than for PID. The upshot is that the rudder moves violently when placed into AxisLock mode.
1 and a half) The assumption that fixed wings are being flown in attitude mode for roll and pitch. AttitudePlus was merged after failsafe, so there was no way to include it at the time, I'm just putting it here since it would need addressing.

For me, these problems are blockers since they either break existing functionality in important ways or exacerbate existing dangers.

*I say can be because coordinate flight only makes sense when you have a yaw actuator. A classic flying wing, for instance, wouldn't use coordinated-flight.

**Comment by peabody124** [comment]
This has been resolved by the refactoring of the controller to configure manual control settings instead of trying to override objects
