### ISSUE TITLE
OSX USB crash

### ISSUE THREAD

**Issue by peabody124** [TauLabs/TauLabs#805]
So I get this crash periodically when plugging in a running board.  Most recently this has been with Sparky but I think it is a general issue.

```[11:01:05.767] [DEBUG] Error writing to device                        qdebug

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000111503d04
[Switching to process 49752 thread 0xde1b]
0x000000010ffb9460 in Sender::run (this=0x111503cf0) at pjrc_rawhid_mac.cpp:224
224	        ret = IOHIDDeviceSetReport(dev, kIOHIDReportTypeOutput, 2, buf, len);
(gdb) bt
#0  0x000000010ffb9460 in Sender::run (this=0x111503cf0) at pjrc_rawhid_mac.cpp:224
#1  0x0000000100253f74 in QThreadPrivate::start ()
#2  0x00007fff86e387a2 in _pthread_start ()
#3  0x00007fff86e251e1 in thread_start ()
(gdb) 
```

The "Error writing to device" error indicates the write thread failed and shuts down, but something appears to try and use it anyway.  Ideally the reason for the underlying write failure would be addressed.  The device isn't permanently locked up because restarting the GCS achieves a valid connection.

**Comment by mlyle** [comment]
Closing these.  While there are still USB-related crashes in OSX, there has been substantial drift since 2013 and new traces should be gathered.
