### ISSUE TITLE
Small GUI BUG: Saving in GCS modules always red cross

### ISSUE THREAD

**Issue by cGiesen** [TauLabs/TauLabs#827]
I see a small error in GCS.

When I save modules settings, I always get an red cross. On Apply and Save.
But in the browser I can see, the values are saved the right way.

My actual Version:
http://jenkins.taulabs.org/artifacts/taulabs_HEAD_20130803_222634_b2fc2b1c6b_win32.exe

And yes, my quanton board has the same firmware ;)

**Comment by peabody124** [comment]
Fixed by #1281 so now it only tries to save objects that are enabled on the FC
