### ISSUE TITLE
Revolution sporadically fails to solve for attitude

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#831]
I'm having a sporadic error where my Revolution board will not solve for attitude. No system alarm error is triggered. Stabilization does not respond to angle, although it does respond to rate. I have not attempted to arm the board, but I suspect it would arm.

I have seen similar behavior before when accidentally saving the AttitudeActual metadata to FlightReadOnly. However, that was not the case here.

The only solution I have found is to unplug the board, wait a few seconds, and try again. Usually the situation resolves itself.

Gyroscope and accelerometer data seem to be normal. FWIW, this board has a bad magnetometer, or at least the magnetometer UAVO is not being written. It is quite deeply installed in my plane, so bisect testing to see if the magnetometer problem is the board or the firmware is not an option.

**Comment by mlyle** [comment]
This is fixed, isn't it?

**Comment by mlyle** [comment]
Closing based on comments and inactivity.
