### ISSUE TITLE
Map widget should refresh whenever there's new position data

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#834]
The map widget should refresh when there's new position data available. Currently the refresh rate is controlled by a timer which is configured through the map's context menu and defaults to 2000ms.

EDIT: @guilhermito pointed out that there is a logical upper bound on increasing refresh rate. So it makes sense to decouple the two after the upper bound.

**Comment by mlyle** [comment]
I dunno.  It's slow enough with redraws that I'm inclined to close.  Comments?

**Comment by mlyle** [comment]
No comments, closing.
