### ISSUE TITLE
Add support for one shot pwm output

### ISSUE THREAD

**Issue by lilvinz** [TauLabs/TauLabs#947]
Like described here:

http://www.multiwii.com/forum/viewtopic.php?f=7&t=2729

http://www.multiwii.com/forum/download/file.php?id=1630&sid=0623051f2324245efeca82df359d0af8&mode=view

**Comment by mlyle** [comment]
There's been a lot of oneshot work and it works great-- flying it on gemini often.  :)  Closed.
