### ISSUE TITLE
Comboboxes get squashed in fixed-wing configuration tab

### ISSUE THREAD

**Issue by kubark42** [TauLabs/TauLabs#948]
![screen shot 2013-09-11 at 10 52 15 am](https://f.cloud.github.com/assets/1118185/1121363/b4397786-1abf-11e3-871a-be0499019707.png)

This doesn't happen in the multirotor configuration tab, so the fix should probably be identical.

**Comment by mlyle** [comment]
Looks not squishy -- or just barely squishy (not like this) -- when i artifically shrink window.  closing.
