### ISSUE TITLE
Ability to define vario deadband for ALT Hold

### ISSUE THREAD

**Issue by readerror67** [TauLabs/TauLabs#952]
Hello,

Spoke on this in the chat, but it would be nice with the TX setting refactoring (expo) if it was possible to change the deadband associated with the altitude hold vario settings.

For example, if one specified 15% then -15% to 15% (from neutral) would have no influence on changes in altitude but anything above or below this would have an effect.

**Comment by peabody124** [comment]
fixed by #1392
